config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects do
    resources :todos
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :todos, -> { order :position }
  accepts_nested_attributes_for :todos, allow_destroy: true
  validates_presence_of :name
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :project
  validates :name, presence: { message: "cannot be blank" }
  validates :position, presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.todos.build
  end

  # GET /projects/1/edit
  def edit
    @project.todos.build if @project.todos.blank?
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(
        :name,
        todos_attributes: [:id, :name, :position, :_destroy])
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:name, :position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Bootstrap CSS classes for flash messages.
  def bootstrap_class_for(flash_type)
    case flash_type
      when :notice
        "alert-info"
      when :success
        "alert-success"
      when :alert
        "alert-warning"
      when :error
        "alert-danger"
      else
        "alert-info " + flash_type.to_s
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Sortable", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Projects", projects_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sortable</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

  <% if @project.errors.any? %>
    <div class="error_explanation alert alert-danger" role="alert">
      <h2><%= pluralize(@project.errors.count, "error") %> prevented this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">

      <div class="well">
        <div class="form-group">
          <%= f.label :name, "Project name", class: "control-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>


      <h2>Todos</h2>

      <div class="nested-fields">
        <ul class="sortable">
        <%= f.fields_for :todos do |ff| %>
          <li>
            <div class="row">
              <div class="col-md-1">
                <i class="handle fa fa-arrows"></i>
              </div>

              <div class="col-md-10">
                <div class="form-group">
                  <%= ff.text_field :name, class: "name form-control" %>
                  <%= ff.hidden_field :_destroy, class: "destroy" %>
                  <%= ff.hidden_field :position, class: "position" %>
                  <%= ff.hidden_field :id, class: "id" %>
                </div>
              </div>

              <div class="col-md-1">
                <i class="remove fa fa-times"></i>
              </div>
            </div>
          </li>
        <% end %>
        </ul>

        <div class="add">
          <i class="fa fa-plus"></i> <a href="#">Add Todo</a>
        </div>
      </div>


      <div class="form-group">
        <%= f.submit "Save", class: "btn btn-primary" %>
        <%= link_to "Cancel", projects_path, class: "btn btn-default" %>
      </div>

    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<h1 class="page-header">Editing Project</h1>

<%= render 'form' %>

<%= link_to 'View this Project', @project %>

app/views/projects/index.html.erb
<h1 class="page-header">Projects</h1>

<% @projects.each do |project| %>
  <h2><%= link_to project.name, project %></h2>
<% end %>

<%= link_to "New Project", new_project_path, class: "btn btn-primary" %>

app/views/projects/new.html.erb
<h1 class="page-header">New Project</h1>

<%= render "form" %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<% if @project.todos.present? %>
  
  <h2>Project Todos</h2>

  <div class="row">
    <div class="col-md-6">
      <ul class="list-group">
      <% @project.todos.each do |todo| %>
        <li class="list-group-item"><%= todo.name %></li>
      <% end %>
      </ul>
    </div>
  </div>

<% else %>

  <div class="well">
    No todos added yet.
    <%= link_to "Add some todos", edit_project_path(@project) %> to your project.
  </div>

<% end %>

<%= link_to "Edit Project", edit_project_path(@project), class: "btn btn-primary" %>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1 class="page-header">Editing Todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1 class="page-header">Listing Todos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1 class="page-header">New Todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<h1 class="page-header">Todo</h1>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>